name: Check Proxies and Update Gist

on:
  # Запуск по расписанию: каждые 6 часов
  schedule:
    - cron: '0 */6 * * *'
  # Позволяет запускать вручную из вкладки Actions в GitHub
  workflow_dispatch:

env:
  # URL со списком прокси для проверки. Замените на свой!
  PROXY_LIST_URL: "https://raw.githubusercontent.com/digitalplantain/proxies_upd/refs/heads/main/sub.txt"
  # Имя файла, который будет создан в Gist
  GIST_FILENAME: "working_proxies.txt"

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Download and setup Xray-core
        run: |
          # Скачиваем последнюю версию Xray для linux-64
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          # Распаковываем
          unzip xray.zip xray
          # Делаем исполняемым
          chmod +x ./xray

      - name: 5. Download proxy list
        run: |
          # Скачиваем список прокси в файл proxies.txt
          curl -s -o proxies.txt ${{ env.PROXY_LIST_URL }}
          echo "Proxy list downloaded."

      - name: 6. Run the proxy checker script
        # Передаем секреты в виде переменных окружения
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_FILENAME: ${{ env.GIST_FILENAME }}
        run: python proxy_checker.py proxies.txt
